name: Test Self-Hosted Runner

on: [push]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Test Command
        run: echo "Hello from Self-Hosted Runner!"
